### PR TITLE
Fix #16

### LINKED ISSUE #16: Always Online does not detect Mojang session server offline.
https://twitter.com/MojangStatus/status/1564526594907062273?cxt=HHwWgoCyscOpqLYrAAAA

Always Online does not detect Mojang **session** server offline.
The auth server was online, but the seesion server was offline.

Is Always Online only checking the auth server?

### PR DESCRIPTION
**Pull request by Pantera07**
This is not tested. If it looks good to you, merge it.

### CODE REVIEW

**Comment by Dablakbandit** [comment]
This definitely will not work, the response checks for Status to be "OK"

**Comment by Pantera07** [comment]
Can it work now?

**Comment by Pantera07** [comment]
sessionserver is an Azure server, and authserver server is an Amazon server. Checking authserver is very strange, because what the server needs is a sessionserver.

**Comment by Pantera07** [comment]
I think this plugin is no longer maintained.

**Pull request closed without merging**
